version: '3.8'

services:
  koy_proxy:
    container_name: koy_proxy
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
      - 4322:80
    networks:
      - koy_frontend
      - koy_backend
    restart: unless-stopped
    depends_on:
      - koy_frontend
  koy_frontend:
    container_name: koy_frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - koy_frontend
    restart: unless-stopped
    depends_on:
      - koy_backend
  koy_backend:
    container_name: koy_backend
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - koy_database
    networks:
      - koy_frontend
      - koy_backend
  koy_database:
    container_name: koy_database
    image: postgres:latest
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - koy_backend
networks:
  koy_frontend:
    name: koy_frontend
  koy_backend:
    name: koy_backend
volumes:
  pgdata:
